export const GET_CARDS = 'GET_CARDS';
export const GET_USERS = 'GET_USERS'
export const GET_CARDS_BY_CATEGORY = 'GET_CARDS_BY_CATEGORY'
export const GET_CARDS_BY_STATUS = 'GET_CARDS_BY_STATUS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'